; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Sat Apr 01 2023 08:00:33 GMT+1000 (Australian Eastern Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


