; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Sat Apr 01 2023 08:00:33 GMT+1000 (Australian Eastern Standard Time)

