; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Sat Apr 01 2023 08:00:33 GMT+1000 (Australian Eastern Standard Time)
; Wait for set temperatures to be reached
M116 P0

