; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v2.1.4 on Sat Jan 04 2020 09:46:45 GMT+1000 (Australian Eastern Standard Time)
;echo "deploying probe"
M98 P"0:/macros/bl_touch/checkProbe.g" ; check the probe for errors etc
M280 P0 S10 ; deploy BLTouch