; sleep.g
; called when M1 (Sleep) is being processed
;
; generated by RepRapFirmware Configuration Tool v2.1.4 on Sat Jan 04 2020 09:46:45 GMT+1000 (Australian Eastern Standard Time)
echo "sleep.g run"

