; tfree2.g
; called when tool 2 is freed
;
; generated by RepRapFirmware Configuration Tool v2.1.4 on Sat Jan 04 2020 09:46:45 GMT+1000 (Australian Eastern Standard Time)
M591 D0 S0 ; disable filament sensor