; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool v2 on Sat Dec 29 2018 20:22:51 GMT+1000 (Australian Eastern Standard Time)
M98 P"0:/sys/homex.g" ; Run home X macro

